version: "3.5"
services:
  
  crdb:
   image: cockroachdb/cockroach:v22.1.2
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
   networks:
     - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - '6379:6379'
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    ports:
      - '26379:26379'
    networks:
      - app-tier
#  backend:
#    build:
#      context: .
#    container_name: voucher
#    command: ["sh", "-c", "sleep 10 && ./voucher"]
#    environment:
#      - WALLET_DATABASE_CONNECTION__ADDRESS=postgresql://root@crdb:26257/defaultdb
#    ports:
#      - "8000:8000"
#    depends_on:
#      - 'crdb'
#      - redis-sentinel
#      - redis
#    networks:
#      - app-tier

volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-tier:
    driver: bridge
