apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voucher.fullname" . }}-secret
  labels:
    {{- include "voucher.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |- {{ tpl (.Files.Get "config/app.yaml") . | nindent 4 }}